In [1]:
import numpy as np

In [8]:
a = np.array([[1, 2], [3, 4], [5, 6]])
res = np.sum(a, axis=1)
x = res.reshape(-1, 1)
x

array([[ 3],
       [ 7],
       [11]])

In [16]:
# 2 in -> 3 hidden

w = np.array(
    [
        [1, 2],
        [-1, -2],
        [3, 1],
    ]
)
print(f"{w=}")

x = np.array([[10], [20]])

print(f"{x=}")

print(w.shape, x.shape)
np.matmul(w, x)

# b = np.array(
#     [

#     ]
# )

w=array([[ 1,  2],
       [-1, -2],
       [ 3,  1]])
x=array([[10],
       [20]])
(3, 2) (2, 1)


array([[ 50],
       [-50],
       [ 50]])

In [17]:
import torch

torch.ones(5, 1)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.]])